export  enum ActionKind {
    LOADING_SHIPS='LOADING_SHIPS',
    LOAD_SHIPS='LOAD_SHIPS',
    LOAD_SHIPS_FAIL='LOAD_SHIPS_FAIL',
    CREATE_SHIP = 'CREATE_SHIP',
    CREATE_SHIP_SUCCESS = 'CREATE_SHIP_SUCCESS',
    CREATE_SHIP_FAIL = 'CREATE_SHIP_FAIL',
    DELETE_SHIP = 'DELETE_SHIP',
    DELETE_SHIP_SUCCESS = 'DELETE_SHIP_SUCCESS',
    DELETE_SHIP_FAIL = 'DELETE_SHIP_FAIL',
    UPDATE_SHIP = 'UPDATE_SHIP',
    UPDATE_SHIP_SUCCESS = 'UPDATE_SHIP_SUCCESS',
    UPDATE_SHIP_FAIL = 'UPDATE_SHIP_FAIL',
}